services:
  psql:
    image: postgres
    user: 1000:1000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aegkerkoebkdsbjwlkthwjthlkewbmklbejlk
    volumes:
      - ./psql:/var/lib/postgresql/data
    ports:
      - 5432:5432