services:
  psql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: S+xyPXPDcYNQtTy3hUNoC9eBwmsoGA
    volumes:
      - ./psql:/var/lib/postgresql/data
    ports:
      - 5555:5432